### ISSUE TITLE
Modifier is not taken into account when determining success/failure

### ISSUE THREAD

**Issue by TALlama** [colinaut/dice-roller#1]
I believe that [this line](https://github.com/colinaut/dice-roller/blob/cc2ac1363dc46e0b7ce445ebe60c8d1cdca7c0f4/src/main.ts#L98) should be:

```
this.success = this.finalTotal >= this.difficulty;
```

**Comment by colinaut** [comment]
Thanks! I'll get this fixed

**Comment by colinaut** [comment]
Ok it's fixed! Thanks

https://github.com/colinaut/dice-roller/releases/tag/v0.2.10
